namespace PsikoAl.Common.Constants;

public static class ErrorKeys
{
    public const string AuthInvalidCredentials = "AUTH_INVALID_CREDENTIALS";
    public const string AuthEmailAlreadyRegistered = "AUTH_EMAIL_ALREADY_REGISTERED";
    public const string AuthEmailInvalid = "AUTH_EMAIL_INVALID";
    public const string AuthWeakPassword = "AUTH_WEAK_PASSWORD";
    public const string AuthEmailNotConfirmed = "AUTH_EMAIL_NOT_CONFIRMED";
    public const string AuthRateLimited = "AUTH_RATE_LIMITED";
    public const string AuthRefreshTokenInvalid = "AUTH_REFRESH_TOKEN_INVALID";
    public const string AuthUserNotFound = "AUTH_USER_NOT_FOUND";
    public const string AuthAccountFrozen = "AUTH_ACCOUNT_FROZEN";
    public const string AuthProviderError = "AUTH_PROVIDER_ERROR";
    public const string ProfileNotFound = "PROFILE_NOT_FOUND";
    public const string AdminUserNotFound = "ADMIN_USER_NOT_FOUND";
    public const string ExpertNotFound = "EXPERT_NOT_FOUND";
    public const string ExpertProfileAlreadyExists = "EXPERT_PROFILE_ALREADY_EXISTS";
    public const string ExpertRoleRequired = "EXPERT_ROLE_REQUIRED";
    public const string ExpertRejectionReasonRequired = "EXPERT_REJECTION_REASON_REQUIRED";
    public const string FileTypeNotAllowed = "FILE_TYPE_NOT_ALLOWED";
    public const string FileTooLarge = "FILE_TOO_LARGE";
    public const string StorageUploadFailed = "STORAGE_UPLOAD_FAILED";
    public const string CategoryNotFound = "CATEGORY_NOT_FOUND";
    public const string CategorySlugAlreadyExists = "CATEGORY_SLUG_ALREADY_EXISTS";
    public const string ReviewNotFound = "REVIEW_NOT_FOUND";
    public const string ReviewAlreadyExists = "REVIEW_ALREADY_EXISTS";
    public const string ReviewClientRoleRequired = "REVIEW_CLIENT_ROLE_REQUIRED";
    public const string ReviewRejectionReasonRequired = "REVIEW_REJECTION_REASON_REQUIRED";
    public const string ListingNotFound = "LISTING_NOT_FOUND";
    public const string ListingClientRoleRequired = "LISTING_CLIENT_ROLE_REQUIRED";
    public const string ListingMaxActiveExceeded = "LISTING_MAX_ACTIVE_EXCEEDED";
    public const string ListingNotOpen = "LISTING_NOT_OPEN";
    public const string ListingNotPendingApproval = "LISTING_NOT_PENDING_APPROVAL";
    public const string ListingRejectionReasonRequired = "LISTING_REJECTION_REASON_REQUIRED";
    public const string ListingReopenNotExpired = "LISTING_REOPEN_NOT_EXPIRED";
    public const string ListingReopenReasonRequired = "LISTING_REOPEN_REASON_REQUIRED";
    public const string SystemSettingNotFound = "SYSTEM_SETTING_NOT_FOUND";
    public const string OfferNotFound = "OFFER_NOT_FOUND";
    public const string OfferAlreadyExists = "OFFER_ALREADY_EXISTS";
    public const string OfferNotPending = "OFFER_NOT_PENDING";
    public const string OfferExpertRoleRequired = "OFFER_EXPERT_ROLE_REQUIRED";
    public const string OfferExpertNotApproved = "OFFER_EXPERT_NOT_APPROVED";
    public const string OfferListingNotOpen = "OFFER_LISTING_NOT_OPEN";
    public const string MatchNotFound = "MATCH_NOT_FOUND";
    public const string MatchNotActive = "MATCH_NOT_ACTIVE";
    public const string MatchNotParticipant = "MATCH_NOT_PARTICIPANT";
    public const string MatchForceReleaseReasonRequired = "MATCH_FORCE_RELEASE_REASON_REQUIRED";
    public const string NotificationNotFound = "NOTIFICATION_NOT_FOUND";
    public const string NotificationTemplateNotFound = "NOTIFICATION_TEMPLATE_NOT_FOUND";
    public const string PushTokenNotFound = "PUSH_TOKEN_NOT_FOUND";
    public const string AssessmentNotFound = "ASSESSMENT_NOT_FOUND";
    public const string AssessmentResultNotFound = "ASSESSMENT_RESULT_NOT_FOUND";
    public const string AssessmentScoreRuleNotFound = "ASSESSMENT_SCORE_RULE_NOT_FOUND";
    public const string ValidationFailed = "VALIDATION_FAILED";
    public const string InternalError = "INTERNAL_ERROR";
}
